<?php 
	
	$config = array(
		'analyticsID' => 'UA-6206955-16',
		'donateButtonHTML' => 'feed <strong>the penguins</strong>',
		'logo' => array(
			'title' => 'Visit Us Online',
			'body' => 'Learn about events and exhibits, purchase tickets, submit feedback, and more!',
			'url' => 'http://www.calacademy.org/explore-science/mobile-apps/penguins'
		),
		'donate' => array(
			'title' => 'Help Advance Our Mission',
			'body' => 'Please visit our website to make a donation.',
			'url' => 'http://www.calacademy.org/donate'
		),
		'error' => array(
			'title' => 'Network Error',
			'body' => 'There appears to be a problem with the network. Would you like to watch a pre-recorded video instead?'
		),
		'flatPlaybackComplete' => array(
			'title' => 'Playback Complete',
			'body' => 'Would you like to watch the video again?'
		)
	);

?>
