<?php 
	
	$config = array(
		'analyticsID' => 'UA-6206955-16',
		'donateButtonHTML' => 'feed <strong>a penguin</strong>',
		'logo' => array(
			'title' => 'Visit Us Online',
			'body' => 'For general Academy information, purchasing tickets, feedback on this app, terms of service and more!',
			'url' => 'http://www.calacademy.org/explore-science/mobile-apps/penguins'
		),
		'donate' => array(
			'title' => 'Help Advance Our Mission',
			'body' => 'Would you like to visit our website to make a donation?',
			'url' => 'http://www.calacademy.org/donate'
		),
		'error' => array(
			'title' => 'Network error',
			'body' => 'Your network connection appears to have been lost. Would you like to watch a short, prerecorded presentation?'
		),
		'flatPlaybackComplete' => array(
			'title' => 'Flat playback complete',
			'body' => 'Would you like to watch it again?'
		)
	);

?>
