<?php

/**
 * Tell Drupal to also look for template files in the modules folder
 * implements hook_theme_registry_alter
 *
 * @param $theme_registry
 */
function calacademy_map_theme_registry_alter(&$theme_registry) {
  $path  = drupal_get_path('module', 'calacademy_map') . '/templates';
  $theme_registry += drupal_find_theme_templates($theme_registry, '.tpl.php', $path);
}

/**
 * Provide node tpl suggestions for the Services Teaser view mode
 * @author grotter
 *
 */
function calacademy_map_preprocess_field(&$vars) {
  if ($vars['element']['#view_mode'] != 'services_teaser') return;
  $vars['theme_hook_suggestions'][] = 'field__services_teaser__hero_region';
}

function calacademy_map_preprocess_node(&$vars) {
  if ($vars['view_mode'] != 'services_teaser') return;
  $vars['theme_hook_suggestions'][] = 'node__services_teaser';
}

/**
 * Implements hook_services_request_postprocess_alter($controller, $args, &$result)
 * Alter the detail field for locations to include relevant data about the referenced entity
 * @author grotter
 *
 */
function calacademy_map_services_request_postprocess_alter($controller, $args, &$result) {
  if (!isset($controller['view info'])) return;

  $viewInfo = $controller['view info'];

  if (!isset($viewInfo['view_name']) || !isset($viewInfo['display_id'])) return;
  if ($viewInfo['view_name'] != 'map_data' || $viewInfo['display_id'] != 'locations') return;

  // set data
  array_walk($result, function ($obj) {
  	if (!empty($obj->detail)) {
  		// see node--services-teaser.tpl.php
      $obj->detail = json_decode($obj->detail);
  	}
  });
}

/**
 * Override or insert variables into the page templates.
 *
 * @param $variables
 *   An array of variables to pass to the theme template.
 * @param $hook
 *   The name of the template being rendered ("page" in this case.)
 */
function calacademy_map_preprocess_page(&$vars) {
  if (request_path() != 'map') return;

  $cssOptions = array('group' => CSS_THEME);

  drupal_add_css(path_to_theme() . '/css/calacademy/page-map.css', $cssOptions);

  $libPath = libraries_get_path('calacademy_map');

  drupal_add_js('//maps.google.com/maps/api/js', 'external');
  drupal_add_js($libPath . '/calacademy_map_data.js');
  drupal_add_js($libPath . '/calacademy_map.js');
  drupal_add_js(drupal_get_path('module', 'calacademy_map') . '/js/calacademy_map_view.js');
  drupal_add_js('jQuery(document).ready(function () { var foo = new CalAcademyMapView(); });', 'inline');
}
