<?php

define('GIGAMACRO_INDEX_PATH', 'gigamacro-floor');

/**
 * Force WYSIWYG on summary in specimen editor
 * @author grotter
 *
 */
function calacademy_gigamacro_field_widget_text_textarea_with_summary_form_alter(&$element, &$form_state, $context) {
  if ($element['#field_name'] == 'body' && $element['#bundle'] == 'gigamacro_specimen') {
    if (isset($element['summary'])) $element['summary']['#wysiwyg'] = true;  
  }
}

/**
 * Add a drag-and-drop interface for pins
 * Implements hook_form_alter(&$form, &$form_state, $form_id)
 * @author grotter
 *
 * @param $form: Nested array of form elements that comprise the form.
 * @param $form_state: A keyed array containing the current state of the form.
 *        The arguments that drupal_get_form() was originally called with are
 *        available in the array $form_state['build_info']['args'].
 * @param $form_id: String representing the name of the form itself. Typically
 *        this is the name of the function that generated the form.
 */

function calacademy_gigamacro_form_alter(&$form, &$form_state, $form_id) {
    // set up pin UI
    if ($form_id == 'gigamacro_pin_node_form' && isset($form['field_geolocation'])) {
        // workaround for hook not firing after form validation fails
        // @see https://www.drupal.org/node/671574
        $form_state['no_cache'] = TRUE;

        $modulePath = drupal_get_path('module', 'calacademy_gigamacro');
        $libPath = libraries_get_path('leaflet');

        drupal_add_css($libPath . '/css/leaflet.css');
        drupal_add_js($libPath . '/js/leaflet.js');
        drupal_add_js($libPath . '/js/leaflet-hacks.js');

        drupal_add_css($modulePath . '/css/calacademy_gigamacro_pin.css');
        drupal_add_js($modulePath . '/js/calacademy_gigamacro_utils.js');
        drupal_add_js($modulePath . '/js/calacademy_gigamacro_pin.js');
        
        drupal_add_js('jQuery(document).ready(function () { var foo = new CalAcademyGigamacroPin(); });', 'inline');
    }
}

function calacademy_gigamacro_preprocess_html(&$vars) {
    if (request_path() != GIGAMACRO_INDEX_PATH) return;
    $vars['classes_array'][] = 'gigamacro-index';
}

function calacademy_gigamacro_preprocess_page(&$page) {
    // some stuff for the specimen viewer
    global $theme;
    if ($theme != 'calacademy_zen') return;

    $isIndex = (request_path() == GIGAMACRO_INDEX_PATH);
    if ($isIndex) http_response_code(200);

    $node = $page['node'];

    if ($isIndex || $node->type == 'gigamacro_specimen') {
        $modulePath = drupal_get_path('module', 'calacademy_gigamacro');
        $libPath = libraries_get_path('leaflet');

        // leaflet
        drupal_add_css($libPath . '/css/leaflet.css');
        drupal_add_js($libPath . '/js/leaflet.js');
        drupal_add_js($libPath . '/js/leaflet-hacks.js');
        
        // leaflet minimap
        drupal_add_css($libPath . '/css/Control.MiniMap.min.css');
        drupal_add_js($libPath . '/js/Control.MiniMap.min.js');

        // jquery slider
        drupal_add_css($libPath . '/css/jquery-ui-slider.min.css');
        drupal_add_js($libPath . '/js/jquery-ui-slider.min.js');
        // drupal_add_js($libPath . '/js/jquery.ui.touch-punch.min.js');

        drupal_add_css(path_to_theme() . '/css/calacademy/node-type-gigamacro-specimen.css');
        drupal_add_css(path_to_theme() . '/css/calacademy/gigamacro-index.css');
        
        drupal_add_js($modulePath . '/js/calacademy_gigamacro_utils.js');
        drupal_add_js($modulePath . '/js/calacademy_gigamacro_index.js');
        drupal_add_js($modulePath . '/js/calacademy_gigamacro_viewer.js');
        
        $arg = $isIndex ? '' : drupal_json_encode($node);
        drupal_add_js('jQuery(document).ready(function () { var foo = new CalAcademyGigamacroViewer(' . $arg . '); });', 'inline');
    }
}
