<?php

/**
 * Add a drag-and-drop interface for pins
 * Implements hook_form_alter(&$form, &$form_state, $form_id)
 * @author grotter
 *
 * @param $form: Nested array of form elements that comprise the form.
 * @param $form_state: A keyed array containing the current state of the form.
 *        The arguments that drupal_get_form() was originally called with are
 *        available in the array $form_state['build_info']['args'].
 * @param $form_id: String representing the name of the form itself. Typically
 *        this is the name of the function that generated the form.
 */

function calacademy_gigamacro_form_alter(&$form, &$form_state, $form_id) {
    if ($form_id != 'gigamacro_pin_node_form') return;
    if (!isset($form['field_geolocation'])) return;

    // workaround for hook not firing after form validation fails
    // @see https://www.drupal.org/node/671574
    $form_state['no_cache'] = TRUE;

    $modulePath = drupal_get_path('module', 'calacademy_gigamacro');
    $libPath = libraries_get_path('leaflet');

    drupal_add_css($libPath . '/css/leaflet.css');
    drupal_add_js($libPath . '/js/leaflet.js');

    drupal_add_css($modulePath . '/css/calacademy_gigamacro_pin.css');
    drupal_add_js($modulePath . '/js/calacademy_gigamacro_pin.js');
    
    drupal_add_js('jQuery(document).ready(function () { var foo = new CalAcademyGigamacroPin(); });', 'inline');
}

function calacademy_gigamacro_preprocess_page(&$page) {
    $node = $page['node'];

    if ($node->type == 'gigamacro_specimen') {
        $modulePath = drupal_get_path('module', 'calacademy_gigamacro');
        $libPath = libraries_get_path('leaflet');

        drupal_add_css($libPath . '/css/leaflet.css');
        drupal_add_js($libPath . '/js/leaflet.js');

        drupal_add_css(path_to_theme() . '/css/calacademy/node-type-gigamacro-specimen.css');
        drupal_add_js($modulePath . '/js/calacademy_gigamacro_viewer.js');
        
        $tid = $node->field_gigamacro_specimen['und'][0]['tid'];

        drupal_add_js('jQuery(document).ready(function () { var foo = new CalAcademyGigamacroViewer(' . $tid . '); });', 'inline');
    }
}
