<?php
/*
This module is for making sure all of the Academy ticket links are up to date and never fall stale.

It populates a vocabulary with data from a json feed provided by IT/Business Applications.

To work correctly, there must be a vocabulary in drupal with the machine name "ticket_links".
There must also be the correct fields with the correct machine names:
1. Name (name)
2. Galaxy Link (field_galaxy_link) - link field type with title and url
3. PLU (field_plu) - text feild - this is ostensibly a unique field and used to reverse lookup products
4. Disabled (field_disabled) - boolean, this is used to exclude certain products from being displayed to the user when selecting ticket links to include on page
5. Product Prices (field_product_prices) - field collection of two text fields (field_product_name and field_price) - a variable number of prices is allowed for each product

*/

  function calacademy_galaxy_init() {

    $vid = db_query("SELECT vid FROM {taxonomy_vocabulary} WHERE machine_name = 'gx_ticketing_links'")->fetchField();

    if(!$vid) {
      taxonomy_vocabulary_save((object) array(
        'name' => 'Galaxy Ticketing Links',
        'machine_name' => 'gx_ticketing_links',
      ));

      $vid = db_query("SELECT vid FROM {taxonomy_vocabulary} WHERE machine_name = 'gx_ticketing_links'")->fetchField();

      $gx_fields = array(
        array('label' => 'Product Name', 'machine_name' => 'field_gx_product_name','type' => 'text', 'widget' => 'text_textfield', 'description' => 'The name of the product'),
        array('label' => 'Product Description', 'machine_name' => 'field_gx_product_description','type' => 'text_long', 'widget' => 'text_textarea', 'description' => 'A brief description of the product'),
        array('label' => 'Product Link', 'machine_name' => 'field_gx_product_link','type' => 'link_field', 'widget' => 'link_field', 'description' => 'The URL to the gateway ticketing store'),
        array('label' => 'Product PLU', 'machine_name' => 'field_gx_product_plu','type' => 'text', 'widget' => 'text_textfield', 'description' => 'The unique PLU of the product'),
        array('label' => 'Disabled', 'machine_name' => 'field_gx_product_disabled','type' => 'list_boolean', 'widget' => 'options_onoff', 'description' => 'Check if the product is defunct')
      //  array('machine_name' => 'field_gx_product_prices','type' => 'text'),
      );

      $gx_field_collection = array(
        array(
          'field' => array(
            'field_name' => 'gx_price_collection',
            'label' => t('Price Type'),
            'cardinality' => FIELD_CARDINALITY_UNLIMITED,
            'type' => 'field_collection',
          ),
          'instance' => array(
            'field_name' => 'gx_price_collection',
            'entity_type' => 'taxonomy_term',
            'bundle' => 'gx_ticketing_links',
            'label' => t('Prices'),
            'cardinality' => FIELD_CARDINALITY_UNLIMITED,
            'description' => '',
            'widget' => array('type' => 'field_collection_embed'),
            'required' => 0,

          ),
        ),
        array(
          'field' => array(
            'field_name' => 'gx_price_label',
            'type' => 'text',
            'label' => 'Price Label',
          ),
          'instance' => array(
            'field_name' => 'gx_price_label',
            'entity_type' => 'field_collection_item',
            'bundle' => 'gx_price_collection',
            'label' => 'Ticket Type',
            'cardinality' => 1,
            'description' => '',
            'widget' => array('type' => 'text_textfield'),
          ),
        ),
        array(
          'field' => array(
            'field_name' => 'gx_price_value',
            'type' => 'text',
            'label' => 'Price',
          ),
          'instance' => array(
            'field_name' => 'gx_price_value',
            'entity_type' => 'field_collection_item',
            'bundle' => 'gx_price_collection',
            'label' => 'Ticket Price',
            'cardinality' => 1,
            'description' => '',
            'widget' => array('type' => 'text_textfield'),
          ),
        ),
      );

      //create product name field and attach to vocabulary
      $i = 3;
      foreach($gx_fields AS $gx_field) {
        field_info_cache_clear();

        if(!field_info_field($gx_field['machine_name'])) {
          $field = array(
            'field_name' => $gx_field['machine_name'],
            'type' => $gx_field['type'],
            'label' => t($gx_field['label'])
          );
          field_create_field($field);
        }

        // Attach the field to our taxonomy entity
        $instance = array(
          'field_name' => $gx_field['machine_name'],
          'entity_type' => 'taxonomy_term',
          'bundle' => 'gx_ticketing_links',
          'label' => t($gx_field['label']),
          'description' => t('Description'),
          'required' => true,
          'widget' => array(
            'type' => $gx_field['widget'],
            'weight' => $i
          ),
        );
        field_create_instance($instance);
        $i++;
      }

      foreach($gx_field_collection AS $fc) {
        field_info_cache_clear();
        if (!field_info_field($fc['field']['field_name'])) {
          field_create_field($fc['field']);
        }
          // Check if instance exists
        if (!field_info_instance($fc['instance']['entity_type'], $fc['instance']['field_name'], $fc['instance']['bundle'])) {
          field_create_instance($fc['instance']);
        }
      }

    }




    //now that we've created the vocabulary and fields, let's populate it with info from the api

    $terms = taxonomy_get_tree($vid);

    include 'example.php';

    $products = json_decode($products);  //get the galaxy product info

    $term_info = array();

    foreach($terms AS $t) {

      $term = taxonomy_term_load($t->tid);

      $plu = field_view_field('taxonomy_term',$term,'field_gx_product_plu',$display = array('label' => 'hidden'));
      $plu = strip_tags(render($plu));

      $term_info[$t->tid] = trim($plu);

    }

    foreach($products AS $product) {

      $product_prices = get_object_vars($product->price);

      if(in_array($product->plu,$term_info)) {

        $tid = array_search($product->plu, $term_info);

        $term = taxonomy_term_load($tid);

        $term->original = $term;
        $term->name = $product->name;
        $term->tid = $tid;
        $term->field_gx_product_name[LANGUAGE_NONE][0]['value'] = $product->name;
        $term->field_gx_product_plu[LANGUAGE_NONE][0]['value'] = $product->plu;
        $term->field_gx_product_link[LANGUAGE_NONE][0]['url'] = $product->url;
        $term->field_gx_product_link[LANGUAGE_NONE][0]['title'] = $product->name;

        $fc_names = array();
        //update existing prices, enter new prices in api that are not in drupal and remove prices in drupal that are not in api

        foreach($term->gx_price_collection[LANGUAGE_NONE] AS &$price) {

          $fc = entity_load('field_collection_item', array($price['value']));

          foreach($fc AS $key => &$item) {
            if (count($item->gx_price_value) > 0)
            {
              $fc_name = strip_tags($item->gx_price_label[LANGUAGE_NONE][0]['value']);
              $fc_names[$fc_name] = strip_tags($item->gx_price_value[LANGUAGE_NONE][0]['value']);
              //if the name/price is already in drupal update it
              if(array_key_exists($fc_name, $product_prices)) {
                $item->gx_price_value[LANGUAGE_NONE][0]['value'] = $product_prices[$fc_name];
              }
              else {
                //delete name/price if it only exists in drupal and not galaxy
                entity_delete('field_collection_item', $key);
              }
            }
          }
        }


        $new_prices = array_diff_key($product_prices,$fc_names);

        foreach($new_prices AS $name => $price) {
          $product_info = taxonomy_term_load($tid);
          $product_prices = entity_create('field_collection_item', array('field_name' => 'gx_price_collection'));
          $product_prices->setHostEntity( 'taxonomy_term', $product_info );

          $product_prices->gx_price_label[LANGUAGE_NONE][0]['value'] = $name;
          $product_prices->gx_price_value[LANGUAGE_NONE][0]['value'] = $price;
          $product_prices->save(FALSE);
        }

      }

      else {

        //create products on api that are not found in drupal
        $term = new stdClass();
        $term->vid = $vid;
        $term->name = $product->name;
        $term->field_gx_product_name[LANGUAGE_NONE][0]['value'] = $product->name;
        $term->field_gx_product_plu[LANGUAGE_NONE][0]['value'] = $product->plu;
        $term->field_galaxy_link[LANGUAGE_NONE][0]['url'] = $product->url;
        $term->field_galaxy_link[LANGUAGE_NONE][0]['title'] = $product->name;

        taxonomy_term_save($term);

        $tid = $term->tid;
        $product_info = taxonomy_term_load($tid);  //tid

        foreach($product->price AS $key => $val) {
          $product_prices = entity_create('field_collection_item', array('field_name' => 'gx_price_collection'));
          $product_prices->setHostEntity( 'taxonomy_term', $product_info );

          //print '<pre>'; print_r($product_info); print '</pre>'; exit;

          $product_prices->gx_price_label[LANGUAGE_NONE][0]['value'] = $key;
          $product_prices->gx_price_value[LANGUAGE_NONE][0]['value'] = $val;
          $product_prices->save(FALSE);
        }

      }

    }
  }

