<?php

  function calacademy_galaxy_init() {

    $vid = db_query("SELECT vid FROM {taxonomy_vocabulary} WHERE machine_name = 'ticket_links'")->fetchField();

  //  print '<pre>vid: '; print_r($vid); print '</pre>';

    $terms = taxonomy_get_tree($vid);

  //  print '<pre>terms: '; print_r($terms); print '</pre>';

    include 'example.php';

    $products = json_decode($products);

    $plus = array();
    foreach($terms AS $t) {

      $term = taxonomy_term_load($t->tid);

  //    print '<pre>term: '; print_r($term); print '</pre>';

      $tplu = field_view_field('taxonomy_term',$term,'field_plu',$display = array('label' => 'hidden'));
      $tplu = strip_tags(render($tplu));

      $plus[] = trim($tplu);

    }

 //   print '<pre>plus: '; print_r($plus); print '</pre>';

    foreach($products AS $product) {

      $plu = $product->plu;
      $url = $product->url;
      $name = $product->name;

      if(in_array($plu, $plus)) {

        print '<p>already here</p>';

      }
      else {

        $term = new stdClass();
        $term->vid = $vid;
        $term->name = $name;
        $term->field_plu[LANGUAGE_NONE][0]['value'] = $plu;
        $term->field_galaxy_link[LANGUAGE_NONE][0]['url'] = $url;
        $term->field_galaxy_link[LANGUAGE_NONE][0]['title'] = $name;

        taxonomy_term_save($term);

        $tid = $term->tid;
        $product_info = taxonomy_term_load($tid);

        foreach($product->price AS $key => $val) {
          $product_prices = entity_create('field_collection_item', array('field_name' => 'field_product_prices'));
          $product_prices->setHostEntity( 'taxonomy_term', $product_info );

          $product_prices->field_product_name['und'][0]['value'] = $key;
          $product_prices->field_price['und'][0]['value'] = $val;
          $product_prices->save( FALSE );
        }

      }
    }
  }


